services:
  compile:
    container_name: compile
    image: minidocks/weasyprint:latest
    volumes:
      - ./:/app
    working_dir: /app
    command: python compile.py

  serve:
    image: nginx:alpine
    container_name: resume-server
    volumes:
      - ./_site:/usr/share/nginx/html
    ports:
      - "127.0.0.1:7777:80"
