services:
  compile:
    container_name: compile
    image: minidocks/weasyprint:latest
    volumes:
      - ./:/app
    working_dir: /app
    command: python generate.py

  resume:
    image: nginx:alpine
    container_name: resume
    volumes:
      - ./_site:/usr/share/nginx/html
    ports:
      - "7777:80"
